name: Update Helm Charts

on:
  release:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  update-helm-charts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install updatecli
        run: |
          sudo apt-get update -y
          sudo curl -LO https://github.com/updatecli/updatecli/releases/download/v0.80.0/updatecli_Linux_x86_64.tar.gz
          sudo tar -zxvf updatecli_Linux_x86_64.tar.gz
          sudo mv updatecli /usr/local/bin
          updatecli version

      - name: Run updatecli
        run: |
          updatecli apply --config updatecli.d/updatecli.yaml --values .github/values.yaml
