name: Update Helm Charts

on: 
  push:
    branches:
      - main  # Specify the branches you want this workflow to run on push

env:
    GITHUB_TOKEN: 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
jobs:
  update-helm-charts:
    runs-on: ubuntu-latest

    steps:
      - name: Install updatecli
        run: |
          sudo curl -LO https://github.com/updatecli/updatecli/releases/download/v0.80.0/updatecli_Linux_x86_64.tar.gz
          sudo tar -zxvf updatecli_Linux_x86_64.tar.gz
          sudo mv updatecli /usr/local/bin
          sudo ls
          sudo pwd


      - name: Run updatecli
        run: |
            cd ..
            sudo ls
            sudo apt-get install tree -y
            sudo tree
            sudo updatecli apply --config updatecli.d/updatecli.yaml
      - name: Run updatecli
        run: |
            sudo updatecli apply --config updatecli/updatecli.yaml --values .github/values.yaml          