name: Update Helm Charts

on: 
  push:
    branches:
      - main  # Specify the branches you want this workflow to run on push

jobs:
  update-helm-charts:
    runs-on: ubuntu-latest

    steps:
      - name: Install updatecli
        run: |
          curl -LO https://github.com/updatecli/updatecli/releases/download/v0.80.0/updatecli_Linux_x86_64.tar.gz
          tar -zxvf updatecli_Linux_x86_64.tar.gz
          mv updatecli /usr/local/bin
          export GITHUB_TOKEN=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


      - name: Run updatecli
        run: |
            updatecli apply --config updatecli.d/updatecli.yaml
      - name: Run updatecli
        run: |
            updatecli apply --config updatecli/updatecli.yaml --values .github/values.yaml          